before:
  hooks:
  - echo "lets package a PHP app ..."

builds:
- lang: php
  flags: --optimize-autoloader

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}'
  wrap_in_directory: false
  files:
    - assets/**/*
    - src/**/*
    - vendor/**/*
    - LICENSE
    - README.md